meta_name: "Le Koinpost"
meta_title: "Le Koinpost - Transformez vos biodéchets"
meta_description: "Soyez bon avec la planète, elle vous le rendra"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards